using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace F1AR.Editor
{
    /// <summary>
    /// Editor utility to automatically create/configure URP Lit materials and assign PBR textures
    /// for the F1 Car model based on material names and texture filename prefixes.
    /// </summary>
    public static class AutoSetupF1Materials
    {
        private const string TexturesFolder = "Assets/Models/AstonMartin/textures";
        private const string MaterialsFolder = "Assets/Models/AstonMartin/Materials";

        [MenuItem("Tools/F1 AR/Setup F1 Car Materials (URP)")]
        public static void SetupMaterials()
        {
            if (!AssetDatabase.IsValidFolder(TexturesFolder))
            {
                Debug.LogError($"[AutoSetupF1Materials] Textures folder not found at '{TexturesFolder}'.");
                return;
            }

            if (!AssetDatabase.IsValidFolder(MaterialsFolder))
            {
                AssetDatabase.CreateFolder("Assets/Models/AstonMartin", "Materials");
            }

            // Find all texture assets in the folder
            string[] textureGuids = AssetDatabase.FindAssets("t:Texture2D", new[] { TexturesFolder });
            List<string> texturePaths = new List<string>();
            foreach (string guid in textureGuids)
            {
                texturePaths.Add(AssetDatabase.GUIDToAssetPath(guid));
            }

            Debug.Log($"[AutoSetupF1Materials] Found {texturePaths.Count} textures. Processing normal maps and materials...");

            // 1. Mark normal maps as NormalMap type in TextureImporter
            foreach (string path in texturePaths)
            {
                if (path.ToLower().Contains("normal"))
                {
                    TextureImporter importer = AssetImporter.GetAtPath(path) as TextureImporter;
                    if (importer != null && importer.textureType != TextureImporterType.NormalMap)
                    {
                        importer.textureType = TextureImporterType.NormalMap;
                        AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
                    }
                }
            }

            // 2. Find all existing materials in project or generated by FBX import
            string[] matGuids = AssetDatabase.FindAssets("t:Material");
            Dictionary<string, Material> existingMaterials = new Dictionary<string, Material>(System.StringComparer.OrdinalIgnoreCase);

            foreach (string guid in matGuids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                Material mat = AssetDatabase.LoadAssetAtPath<Material>(path);
                if (mat != null && !existingMaterials.ContainsKey(mat.name))
                {
                    existingMaterials.Add(mat.name, mat);
                }
            }

            Shader urpLitShader = Shader.Find("Universal Render Pipeline/Lit");
            if (urpLitShader == null)
            {
                urpLitShader = Shader.Find("Standard");
            }

            int configuredCount = 0;

            // Iterate over texture paths and match to materials
            foreach (string texPath in texturePaths)
            {
                Texture2D tex = AssetDatabase.LoadAssetAtPath<Texture2D>(texPath);
                if (tex == null) continue;

                string filename = Path.GetFileNameWithoutExtension(texPath);
                
                // Texture naming pattern: formula2v4nomaterila_[MATNAME]_[MAPTYPE].png
                // Extract material keyword
                string cleanName = filename.Replace("formula2v4nomaterila_", "");
                
                string matKey = "";
                string mapType = "";

                if (cleanName.Contains("_BaseCol")) { mapType = "BaseMap"; matKey = cleanName.Substring(0, cleanName.IndexOf("_BaseCol")); }
                else if (cleanName.Contains("_Normal")) { mapType = "Normal"; matKey = cleanName.Substring(0, cleanName.IndexOf("_Normal")); }
                else if (cleanName.Contains("_Metal")) { mapType = "Metallic"; matKey = cleanName.Substring(0, cleanName.IndexOf("_Metal")); }
                else if (cleanName.Contains("_Rough")) { mapType = "Roughness"; matKey = cleanName.Substring(0, cleanName.IndexOf("_Rough")); }
                else if (cleanName.Contains("_Height")) { mapType = "Height"; matKey = cleanName.Substring(0, cleanName.IndexOf("_Height")); }

                if (string.IsNullOrEmpty(matKey)) continue;

                // Strip numbers/suffixes like _2, _5 if needed, or match directly
                Material targetMat = FindBestMatchingMaterial(matKey, existingMaterials, urpLitShader);
                if (targetMat != null)
                {
                    Undo.RecordObject(targetMat, "Assign F1 Texture");

                    if (mapType == "BaseMap")
                    {
                        targetMat.SetTexture("_BaseMap", tex);
                        targetMat.SetTexture("_MainTex", tex);
                    }
                    else if (mapType == "Normal")
                    {
                        targetMat.SetTexture("_BumpMap", tex);
                        targetMat.EnableKeyword("_NORMALMAP");
                    }
                    else if (mapType == "Metallic")
                    {
                        targetMat.SetTexture("_MetallicGlossMap", tex);
                        targetMat.EnableKeyword("_METALLICSPECGLOSSMAP");
                    }

                    EditorUtility.SetDirty(targetMat);
                    configuredCount++;
                }
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"[AutoSetupF1Materials] Successfully updated F1 materials with PBR textures!");
        }

        private static Material FindBestMatchingMaterial(string key, Dictionary<string, Material> existingMaterials, Shader fallbackShader)
        {
            // Direct match
            foreach (var kvp in existingMaterials)
            {
                if (kvp.Key.Equals(key, System.StringComparison.OrdinalIgnoreCase) ||
                    kvp.Key.Contains(key, System.StringComparison.OrdinalIgnoreCase) ||
                    key.Contains(kvp.Key, System.StringComparison.OrdinalIgnoreCase))
                {
                    return kvp.Value;
                }
            }

            // Create new material if not found
            string newMatPath = $"{MaterialsFolder}/{key}.mat";
            Material newMat = AssetDatabase.LoadAssetAtPath<Material>(newMatPath);
            if (newMat == null)
            {
                newMat = new Material(fallbackShader);
                newMat.name = key;
                AssetDatabase.CreateAsset(newMat, newMatPath);
                existingMaterials[key] = newMat;
            }

            return newMat;
        }
    }
}
